---
author: Adam Twardoch <adam+npm@twardoch.com> (https://twardoch.github.io/)
bugs:
  url: https://github.com/twardoch/markdownlp/issues
dependencies:
  '@textlint/ast-tester': latest
  '@textlint/ast-traverse': latest
  '@textlint/fixer-formatter': latest
  '@textlint/linter-formatter': latest
  '@textlint/markdown-to-ast': latest
  '@textlint/text-to-ast': latest
  '@textlint/textlint-plugin-markdown': latest
  '@textlint/textlint-plugin-text': latest
  '@vcarl/remark-headings': latest
  mdast-add-list-metadata: latest
  mdast-builder: latest
  mdast-comment-marker: latest
  mdast-flatten-image-paragraphs: latest
  mdast-flatten-listitem-paragraphs: latest
  mdast-flatten-nested-lists: latest
  mdast-move-images-to-root: latest
  mdast-normalize-headings: latest
  mdast-squeeze-paragraphs: latest
  mdast-util-assert: latest
  mdast-util-compact: latest
  mdast-util-definitions: latest
  mdast-util-from-quill-delta: latest
  mdast-util-heading-range: latest
  mdast-util-heading-style: latest
  mdast-util-inject: latest
  mdast-util-phrasing: latest
  mdast-util-to-hast: latest
  mdast-util-to-nlcst: latest
  mdast-util-to-string: latest
  mdast-util-toc: latest
  mdast-zone: latest
  rehype: latest
  rehype-accessible-emojis: latest
  rehype-add-classes: latest
  rehype-attr: latest
  rehype-autolink-headings: latest
  rehype-citation: latest
  rehype-cli: latest
  rehype-code-title: latest
  rehype-concat-css-style: latest
  rehype-concat-javascript: latest
  rehype-css-modules: latest
  rehype-css-to-top: latest
  rehype-document: latest
  rehype-dom: latest
  rehype-dom-parse: latest
  rehype-dom-stringify: latest
  rehype-external-links: latest
  rehype-figure: latest
  rehype-figure-for-img: latest
  rehype-footnotes-title: latest
  rehype-format: latest
  rehype-highlight: latest
  rehype-html-blocks: latest
  rehype-ignore: latest
  rehype-infer-description-meta: latest
  rehype-infer-reading-time-meta: latest
  rehype-infer-title-meta: latest
  rehype-inline: latest
  rehype-inline-svg: latest
  rehype-javascript-to-bottom: latest
  rehype-join-line: latest
  rehype-katex: latest
  rehype-lodash-template: latest
  rehype-mathjax: latest
  rehype-meta: latest
  rehype-minify-attribute-whitespace: latest
  rehype-minify-css-style: latest
  rehype-minify-doctype: latest
  rehype-minify-enumerated-attribute: latest
  rehype-minify-event-handler: latest
  rehype-minify-javascript-script: latest
  rehype-minify-javascript-url: latest
  rehype-minify-json-script: latest
  rehype-minify-language: latest
  rehype-minify-media-attribute: latest
  rehype-minify-meta-color: latest
  rehype-minify-meta-content: latest
  rehype-minify-style-attribute: latest
  rehype-minify-url: latest
  rehype-minify-whitespace: latest
  rehype-normalize-attribute-value-case: latest
  rehype-parse: latest
  rehype-partials: latest
  rehype-picture: latest
  rehype-plugin-image-native-lazy-loading: latest
  rehype-postcss: latest
  rehype-postfix-footnote-anchors: latest
  rehype-preset-minify: latest
  rehype-prevent-favicon-request: latest
  rehype-prism-plus: latest
  rehype-raw: latest
  rehype-react: latest
  rehype-remark: latest
  rehype-remove-comments: latest
  rehype-remove-duplicate-attribute-values: latest
  rehype-remove-empty-attribute: latest
  rehype-remove-external-script-content: latest
  rehype-remove-meta-http-equiv: latest
  rehype-remove-script-type-javascript: latest
  rehype-remove-style-type-css: latest
  rehype-remove-unused-css: latest
  rehype-resolution: latest
  rehype-retext: latest
  rehype-rewrite: latest
  rehype-sanitize: latest
  rehype-shift-heading: latest
  rehype-shiki: latest
  rehype-slug-custom-id: latest
  rehype-sort-attribute-values: latest
  rehype-sort-attributes: latest
  rehype-sort-tailwind-classes: latest
  rehype-stringify: latest
  rehype-template: latest
  rehype-toc: latest
  rehype-truncate: latest
  rehype-twemojify: latest
  rehype-url-inspector: latest
  rehype-urls: latest
  rehype-video: latest
  rehype-widont: latest
  rehype-wrap: latest
  rehype-wrap-all: latest
  remark: latest
  remark-a11y-emoji: latest
  remark-abbr: latest
  remark-admonitions: latest
  remark-align: latest
  remark-application-links: latest
  remark-attr: latest
  remark-autolink-headings: latest
  remark-autolink-references: latest
  remark-behead: latest
  remark-bookmarks: latest
  remark-bracketed-spans: latest
  remark-breaks: latest
  remark-capitalize: latest
  remark-cite: latest
  remark-cli: latest
  remark-code-blocks: latest
  remark-code-extra: latest
  remark-code-frontmatter: latest
  remark-code-import: latest
  remark-code-screenshot: latest
  remark-codesandbox: latest
  remark-collapse: latest
  remark-comment-blocks: latest
  remark-comment-config: latest
  remark-comments: latest
  remark-container: latest
  remark-containers: latest
  remark-contributors: latest
  remark-copy-linked-files: latest
  remark-cross-reference: latest
  remark-definition-list: latest
  remark-defsplit: latest
  remark-devim: latest
  remark-directive: latest
  remark-directive-rehype: latest
  remark-disable-tokenizers: latest
  remark-docx: latest
  remark-dropcap: latest
  remark-embed-images: latest
  remark-emoji: latest
  remark-emoji-to-gemoji: latest
  remark-extended-table: latest
  remark-external-links: latest
  remark-extract-frontmatter: latest
  remark-extract-toc: latest
  remark-fenced-divs: latest
  remark-fix-guillemets: latest
  remark-footnotes: latest
  remark-frontmatter: latest
  remark-gemoji: latest
  remark-gemoji-to-emoji: latest
  remark-generic-extensions: latest
  remark-gfm: latest
  remark-git-contributors: latest
  remark-github: latest
  remark-github-beta-blockquote-admonitions: latest
  remark-gitlab-artifact: latest
  remark-graphviz: latest
  remark-grid-tables: latest
  remark-heading-gap: latest
  remark-heading-id: latest
  remark-heading-shift: latest
  remark-heading-trailing-spaces: latest
  remark-highlight.js: latest
  remark-hint: latest
  remark-html: latest
  remark-html-emoji-image: latest
  remark-html-katex: latest
  remark-iframes: latest
  remark-images: latest
  remark-img-links: latest
  remark-include: latest
  remark-inline-links: latest
  remark-join-cjk-lines: latest
  remark-kbd: latest
  remark-kbd-plus: latest
  remark-license: latest
  remark-linkify-regex: latest
  remark-lint: latest
  remark-lint-alphabetize-lists: latest
  remark-lint-appropriate-heading: latest
  remark-lint-are-links-valid: latest
  remark-lint-blank-lines-1-0-2: latest
  remark-lint-blockquote-indentation: latest
  remark-lint-books-links: latest
  remark-lint-checkbox-character-style: latest
  remark-lint-checkbox-content-indent: latest
  remark-lint-code-block-style: latest
  remark-lint-definition-case: latest
  remark-lint-definition-spacing: latest
  remark-lint-emphasis-marker: latest
  remark-lint-fenced-code-flag: latest
  remark-lint-fenced-code-marker: latest
  remark-lint-file-extension: latest
  remark-lint-final-definition: latest
  remark-lint-final-newline: latest
  remark-lint-first-heading-level: latest
  remark-lint-hard-break-spaces: latest
  remark-lint-heading-increment: latest
  remark-lint-heading-style: latest
  remark-lint-link-title-style: latest
  remark-lint-list-item-bullet-indent: latest
  remark-lint-list-item-content-indent: latest
  remark-lint-list-item-indent: latest
  remark-lint-list-item-spacing: latest
  remark-lint-maximum-heading-length: latest
  remark-lint-maximum-line-length: latest
  remark-lint-no-auto-link-without-protocol: latest
  remark-lint-no-blockquote-without-marker: latest
  remark-lint-no-consecutive-blank-lines: latest
  remark-lint-no-dead-urls: latest
  remark-lint-no-duplicate-definitions: latest
  remark-lint-no-duplicate-headings: latest
  remark-lint-no-emphasis-as-heading: latest
  remark-lint-no-empty-sections: latest
  remark-lint-no-file-name-articles: latest
  remark-lint-no-file-name-consecutive-dashes: latest
  remark-lint-no-file-name-irregular-characters: latest
  remark-lint-no-file-name-mixed-case: latest
  remark-lint-no-file-name-outer-dashes: latest
  remark-lint-no-heading-content-indent: latest
  remark-lint-no-heading-indent: latest
  remark-lint-no-heading-punctuation: latest
  remark-lint-no-html: latest
  remark-lint-no-inline-padding: latest
  remark-lint-no-literal-urls: latest
  remark-lint-no-missing-blank-lines: latest
  remark-lint-no-multiple-toplevel-headings: latest
  remark-lint-no-shell-dollars: latest
  remark-lint-no-shortcut-reference-image: latest
  remark-lint-no-shortcut-reference-link: latest
  remark-lint-no-table-indentation: latest
  remark-lint-no-tabs: latest
  remark-lint-no-undefined-references: latest
  remark-lint-no-unused-definitions: latest
  remark-lint-no-url-trailing-slash: latest
  remark-lint-ordered-list-marker-style: latest
  remark-lint-ordered-list-marker-value: latest
  remark-lint-rule-style: latest
  remark-lint-strong-marker: latest
  remark-lint-table-cell-padding: latest
  remark-lint-table-pipe-alignment: latest
  remark-lint-table-pipes: latest
  remark-lint-unordered-list-marker-style: latest
  remark-lint-write-good: latest
  remark-macro: latest
  remark-man: latest
  remark-mark: latest
  remark-math: latest
  remark-mdx: latest
  remark-merge: latest
  remark-mermaidjs: latest
  remark-message-control: latest
  remark-meta: latest
  remark-metadata: latest
  remark-multiline-code: latest
  remark-normalize-headings: latest
  remark-numbered-footnote-labels: latest
  remark-oembed: latest
  remark-openapi: latest
  remark-parse: latest
  remark-parse-yaml: latest
  remark-pdf: latest
  remark-ping: latest
  remark-preset-lint-consistent: latest
  remark-preset-lint-dealerdirect: latest
  remark-preset-lint-markdown-style-guide: latest
  remark-preset-lint-recommended: latest
  remark-preset-wooorm: latest
  remark-prettier: latest
  remark-prism: latest
  remark-react: latest
  remark-react-codemirror: latest
  remark-react-lowlight: latest
  remark-redact: latest
  remark-redactable: latest
  remark-reference-links: latest
  remark-rehype: latest
  remark-relative-links: latest
  remark-remove-comments: latest
  remark-responsive-tables: latest
  remark-retext: latest
  remark-sectionize: latest
  remark-shortcodes: latest
  remark-slate: latest
  remark-slate-transformer: latest
  remark-slug: latest
  remark-smartypants: latest
  remark-smcat: latest
  remark-sources: latest
  remark-squeeze-paragraphs: latest
  remark-stringify: latest
  remark-strip-badges: latest
  remark-strip-html: latest
  remark-sub-super: latest
  remark-terms: latest
  remark-textr: latest
  remark-title: latest
  remark-toc: latest
  remark-torchlight: latest
  remark-trim: latest
  remark-truncate-links: latest
  remark-twemoji: latest
  remark-typedoc-symbol-links: latest
  remark-typescript: latest
  remark-typograf: latest
  remark-unlink: latest
  remark-unwrap-images: latest
  remark-unwrap-texts: latest
  remark-usage: latest
  remark-utf8: latest
  remark-validate-links: latest
  remark-variables: latest
  remark-vdom: latest
  remark-wiki-link: latest
  remark-with-images: latest
  remark-yaml-config: latest
  remarkable: latest
  retext: latest
  retext-assuming: latest
  retext-cliches: latest
  retext-contractions: latest
  retext-diacritics: latest
  retext-dutch: latest
  retext-emoji: latest
  retext-english: latest
  retext-equality: latest
  retext-indefinite-article: latest
  retext-intensify: latest
  retext-keywords: latest
  retext-latin: latest
  retext-no-emojis: latest
  retext-overuse: latest
  retext-passive: latest
  retext-pos: latest
  retext-profanities: latest
  retext-quotes: latest
  retext-readability: latest
  retext-redundant-acronyms: latest
  retext-repeated-words: latest
  retext-sentence-spacing: latest
  retext-simplify: latest
  retext-smartypants: latest
  retext-spell: latest
  retext-stringify: latest
  retext-syntax-mentions: latest
  retext-syntax-mentions-channels: latest
  retext-syntax-urls: latest
  retext-textlint: latest
  retext-usage: latest
  retext-use-contractions: latest
  textlint: latest
  textlint-filter-rule-comments: latest
  textlint-rule-alex: latest
  textlint-rule-apostrophe: latest
  textlint-rule-diacritics: latest
  textlint-rule-ginger: latest
  textlint-rule-helper: latest
  textlint-rule-no-dead-link: latest
  textlint-rule-no-todo: latest
  textlint-rule-preset-jtf-style: latest
  textlint-rule-rousseau: latest
  textlint-rule-spellchecker: latest
  textlint-rule-stop-words: latest
  textlint-rule-terminology: latest
  textlint-rule-write-good: latest
  textlint-scripts: latest
  textlint-tester: latest
  typographic: latest
  typographic-apostrophes: latest
  typographic-apostrophes-for-possessive-plurals: latest
  typographic-arrows: latest
  typographic-base: latest
  typographic-colon: latest
  typographic-copyright: latest
  typographic-ellipses: latest
  typographic-em-dash: latest
  typographic-em-dashes: latest
  typographic-en-dashes: latest
  typographic-exclamation-mark: latest
  typographic-guillemets: latest
  typographic-markdown: latest
  typographic-math-symbols: latest
  typographic-numbers: latest
  typographic-orphan: latest
  typographic-percent: latest
  typographic-permille: latest
  typographic-question-mark: latest
  typographic-quotes: latest
  typographic-registered-trademark: latest
  typographic-semicolon: latest
  typographic-single-spaces: latest
  typographic-trademark: latest
  unified-args: latest
  unified-engine: latest
  unified-lint-rule: latest
  unified-message-control: latest
  unified-stream: latest
description: Collection of NLP tools for Markdown (mostly using Python)
homepage: https://github.com/twardoch/markdownlp#readme
keywords: []
license: MIT
main: index.js
name: markdownlp
repository:
  type: git
  url: git+https://github.com/twardoch/markdownlp.git
scripts:
  test: 'echo "Error: no test specified" && exit 1'
version: 1.0.0